### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by rossmoody** [mortenjust/SwiftUIWindow#1]

**Comment by rossmoody** [comment]
It might be my environment, but I did have to structure the simple example from the README to work like this:

```
SwiftUIWindow.open { _ in
            Text("Hello new window")
                .frame(width: 400, height: 200) // window size
        }
```

**Comment by mortenjust** [comment]
Thanks for letting me know. Fixed. Also added a link to the new Window API in Swiftui 4 (macOS Ventura)
